const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR = 'FETCH_ERROR';

const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';

const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';

const COMPLETED_NOTE_SUCCESS = 'COMPLETED_NOTE_SUCCESS';
const COMPLETED_NOTE_ERROR = 'COMPLETED_NOTE_ERROR';

const FILTER_NOTES = 'FILTER_NOTES';

export {
  ADD_NOTE_SUCCESS,
  ADD_NOTE_ERROR,
  DELETE_NOTE_SUCCESS,
  DELETE_NOTE_ERROR,
  COMPLETED_NOTE_SUCCESS,
  COMPLETED_NOTE_ERROR,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  FILTER_NOTES,
};
